const actions = {
  FETCH_ACCESS_TOKEN: 'FETCH_ACCESS_TOKEN',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  FETCH_RANDOM_DOGS: 'FETCH_RANDOM_DOGS',
  SET_RANDOM_DOGS: 'SET_RANDOM_DOGS'
};

export default actions;
