const actions = {
  FETCH_ACCESS_TOKEN: 'FETCH_ACCESS_TOKEN',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_SEARCH_LOCATION: 'SET_SEARCH_LOCATION',
  FETCH_PETS: 'FETCH_PETS',
  SET_PETS: 'SET_PETS',
  FETCH_PET: 'FETCH_PET',
  SET_PET: 'SET_PET'
};

export default actions;
